### ISSUE TITLE
 Error: Error setting status: Not Found

### ISSUE THREAD

**Issue by eloisetaylor5693** [maxisam/check-report#131]
I see the error below in our pipeline when using this github action

## Yaml

```yaml
permissions:
  checks: write
  contents: read
  packages: read
  pull-requests: write

jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: node-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile --check-files
      - run: yarn test --coverage

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both

      - name: Comment build
        if: always()
        run: |
          cat code-coverage-results.md >> "$GITHUB_STEP_SUMMARY"

      - name: Create Check
        uses: maxisam/check-report@v0.2.0
        with:
          authToken: ${{ env.GITHUB_PACKAGES_TOKEN }}
          checkName: 'Code Coverage Report'
          summary: 'Code Coverage Report'
          status: 'completed'
          content: |
              ## content
          detailsUrl: 'https://github.com/maxisam/check-report'
```

## Error

The status in the request looks like it should be ok since it matches the value in the docs: https://docs.github.com/en/free-pro-team@latest/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
```
 Error: Error setting status:
Not Found
Request object:
{
  "owner": "<owner>",
  "repo": "<repo>",
  "name": "Code Coverage Report",
  "head_sha": "6ed8631dd98eb1793617792f1fe5059106082dba",
  "status": "completed",
  "details_url": "https://github.com/maxisam/check-report",
  "conclusion": "success",
  "output": {
    "title": "Code Coverage Report",
    "summary": "Code Coverage Report",
    "text": "## content",
    "images": [
      {
        "alt": "Code Coverage Report",
        "image_url": "https://avatars.githubusercontent.com/in/15368?s=40&v=4",
        "caption": "Code Coverage Report"
      }
    ]
  }
}
```
